---
title: "Coursera Data Science Capstone Project"
author: "Robert Levine"
date: "February 2020"
output: slidy_presentation
---


## Project Overview


The capstone project goal was to build a text predictive algorithm using natural language processing and text mining.  The model was created using the Shiny application in RStudio.

The source data for this project can be found at: https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip

My Shiny App can be found at: https://rlshiny.shinyapps.io/WordPredictionRL/

My source code is located on GitHub at: https://github.com/RL-coursera/datasciencecoursera/tree/capstone

## Working with the Data 

In order to build a prediction algorithm, data was scraped from blogs, twitter and the news.  The data processing was as follows:

- The data was read into R
- Data cleaning was performed: stripping out numbers and punctuation, changing all text to lowercase and removing whitespace.
- N-grams were created - these are a sequence of items collected from a corpus.  The N refers to the number of items within the sequence.  For this project, bigrams, trigrams and quadgrams were used.
- The N-grams were sorted and the metadata saved as an .rds file.

## The Prediction Model 

The model for the next word prediction was based on the Katz Back-off algorithm.  This works as follows:

- The .rds files containing the metadata are loaded.
- The quadgram is the first N-gram to be used.  This supports prediction based on three words that user has provided.
- If no match is found, the trigram is used.  This takes the last two words of the user input into account.
-  If there is still no match found, the bigram is used. Bigram only uses the last word of the user input. 
- When no match is found, the application will return a comment that no match is found due to the small sample size.



